name: MedTel Deploy Workflow

on:
  pull_request:
  push:
    branches:
      - "master"
      - "*"
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    working-directory: apps/firstApp

jobs:
  build:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - name: Invoke First App workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Building First App
          token: ${{ secrets.CI_TOKEN }}
          inputs: '{ "run_id": "${{ github.run_id }}" }'
  deploy:
    name: Deploy to Github Pages
    #    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve build files
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.run_id }}_BUILD
          path: apps/firstApp/www
      - name: Create deploy folder
        run: |
          mkdir ${{ github.workspace }}/deploy
          mkdir ${{ github.workspace }}/deploy/apps
          mkdir ${{ github.workspace }}/deploy/apps/FirstWebApp
      - name: Copy to FirstWebApp to deploy folder
        run: cp -r www ${{ github.workspace }}/deploy/apps/FirstWebApp
      - name: Copy root app to deploy folder
        run: |
          cp ${{ github.workspace }}/index.html ${{ github.workspace }}/deploy
          cp -r ${{ github.workspace }}/css ${{ github.workspace }}/deploy
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy
