name: Building First App

on:
#  pull_request:
#  push:
#    branches:
#      - "master"
#      - "*"
#  schedule:
#    - cron: "0 0 * * *"
#
  workflow_dispatch:

defaults:
  run:
    working-directory: apps/firstApp

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: ${{ github.ref }}
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Persist build files
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.run_id }}_BUILD
          path: apps/firstApp/www
